### ISSUE TITLE
可连接aria2以及webui，但发送下载至aria2无效，只能手动将链接填入webui或yaaw中进行下载。

### ISSUE THREAD

**Issue by samuraimaria** [CiChui/Ci-Aria2BDY#1]
可连接aria2以及webui，但发送下载至aria2无效，只能手动将链接填入webui或yaaw中进行下载。

**Comment by CiChui** [comment]
请提供下网盘分享地址，我这里测试推送下载没问题！

**Comment by samuraimaria** [comment]
https://pan.baidu.com/s/1i6sRPbR, 比如这个，我装好脚本后第一次运行会提示连接域名，点允许后，推送显示成功，但yaaw里无接收命令，很奇怪，重启浏览器也没用，感觉是权限问题？有个叫CX-百度云盘的脚本没问题，可以正常推送，但没有webui，我想要个webui啊。

**Comment by CiChui** [comment]
目前确认为RPC令牌未设置导致推送下载出错，两种解决方式
1.在你的服务端配置中设置RPC令牌，并填入下载设置中以提高安全性；
2.服务端未设置RPC令牌，只需在下载设置中随便填写一个令牌保存即可

**Comment by samuraimaria** [comment]
感谢大师，已解决，确实是RPC令牌问题，随便填写后可以正常推送。希望以后更新能解决这个bug。。
