### ISSUE TITLE
同样是aria2的推送问题

### ISSUE THREAD

**Issue by toobye** [CiChui/Ci-Aria2BDY#2]
选取资源后选择ciaria2-下载，会报没有router错误导致无法添加下载的文件，但是点击ciaria2-管理又可以正常进入aria界面，不知道是不是我的操作问题，更换资源或者重新打开浏览器依旧如此
Ci-Aria2BDY:程序异常
请尝试更新脚本或复制以下信息提交issue

Exception: TypeError: Cannot read property 'router' of null

Script Ver: 1.2.0

TemperMonkey Ver: 4.5

UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

**Comment by samuraimaria** [comment]
目前确认为RPC令牌未设置导致推送下载出错，两种解决方式
1.在你的服务端配置中设置RPC令牌，并填入下载设置中以提高安全性；
2.服务端未设置RPC令牌，只需在下载设置中随便填写一个令牌保存即可
以上是原作者的解决方案，实测有效。Aria2服务器令牌处随便填个数字就行了
额 又仔细看了下你的问题，好像和我的还不太一样。

**Comment by CiChui** [comment]
清除缓存，重新安装脚本！

**Comment by py930828** [comment]
作者你好，谢谢您的作品，目前我怎么尝试都无法添加任务到aria2,问题是点击下载后只会显示发送任务到aria2,但是没有任何反应，请问是什么情况呢？aria2正常工作，用百度网盘助手插件能正常使用。推送链接确认正确。

Edit: 刚刚找到原因了，需要在RPC令牌里面输入一个值，随便任何值都行，即使aria2没有设置令牌。要不无法推送到aria2，希望能解决这个BUG~~~~谢谢！！
