### ISSUE TITLE
脚本出错了，无法加载

### ISSUE THREAD

**Issue by iloeng** [CiChui/Ci-Aria2BDY#3]
![s-20180605-131621](https://user-images.githubusercontent.com/31269745/40956430-d3f35c9e-68c2-11e8-9cc7-288a73d1bea4.png)

**Comment by TomsSawyer** [comment]
同遇到一样的报错

**Comment by York-Cheung** [comment]
同遇到一样的报错

**Comment by CiChui** [comment]
已更新！
