### ISSUE TITLE
Exception: TypeError: Illegal constructor

### ISSUE THREAD

**Issue by flute** [CiChui/Ci-Aria2BDY#5]
Exception: TypeError: Illegal constructor

Script Ver: 1.2.3

TemperMonkey Ver: 4.7

UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by CiChui** [comment]
请具体描述
1.出现错误的场景(什么操作后出现)
2.脚本的使用环境
3.尝试过的解决方案
