### ISSUE TITLE
文件无法下载

### ISSUE THREAD

**Issue by tshu-w** [CiChui/Ci-Aria2BDY#9]
Script Ver: 1.2.3
TemperMonkey Ver: 4.8.5847
macOS Mojave 10.14.1
Safari

不知道和这个 [issue](https://github.com/acgotaku/BaiduExporter/issues/620) 是否有关，但用 BaiduExporter 登录后可以下载

**Comment by mk2016a** [comment]
Same issue
成功发送，无法下载。

【文件夹】Top Gear UK All In One.zip
  download was unsuccessful    0 B    /mnt//sda/sda1
